backend:
  name: github
  repo: grantballmer/test-repo
media_folder: static/assets
public_folder: assets
collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: body, label: Body, widget: markdown }
      - {
          label: Template Key,
          name: templateKey,
          widget: "hidden",
          default: "blogTemplate",
        }

  - name: band
    label: Band
    folder: src/pages/roster
    create: true
    identifier_field: name
    fields:
      - { name: slug, label: Path }
      - { name: name, label: Name }
      - { name: genre, label: Genre }
      - { name: bio, label: Band Bio, widget: markdown }
      - { name: thumbnail, label: Roster Page Thumbnail, widget: image }
      - { name: banner, label: Band Page Banner, widget: image }
      - label: Social Media
        name: social
        widget: list
        fields:
          - { label: Spotify Link, name: spotify }
          - { label: Youtube Link, name: youtube }
          - { label: iTunes Link, name: itunes }
          - { label: Facebook Link, name: facebook }
          - { label: Instagram Link, name: instagram }
      - label: Management
        name: management
        widget: list
        allow_add: true
        fields:
          - { label: Position, name: position }
          - { label: Name, name: name }
          - { label: Email, name: email }
      - {
          label: Template Key,
          name: templateKey,
          widget: "hidden",
          default: "bandTemplate",
        }
